// COPYRIGHT (C) HARRY CLARK 2025
// CS3_CI EVOLUTIONARY COMPUTATION 

// THIS FILE PERTAINS TOWARDS AN EXAMPLE OF HOW UTILISING CROSSOVER
// ALLOWS FOR THE GRADUAL MUTATION/REPRODUCTION OF AN ALGORITHM OVER THE COURSE
// OF IT'S RUNTIME

// NESTED INCLUDES

#include "crossover.h"

// CALCULATES THE COUNT MATCHING CHARACTERS AGAINST THE TARGET STRING
// THIS IS IN RELATION TO THE WELLNESS OF THE PERSON IN QUESTION

// THE WELLNESS WILL BE EXPANDED THROUGH THE EVOLUTION OF THE PROGRAM

int FITNESS_CALC(char* MATCH)
{
    int MATCHING_CHARS = 0;
    for(int INDEX = 0; INDEX < EC_STRLEN; INDEX++)
    {
        if(MATCH[INDEX] == EC_STRING[INDEX]) { MATCHING_CHARS++; }
    }

    return MATCHING_CHARS;
}
