// COPYRIGHT (C) HARRY CLARK 2025
// CS3_CI EVOLUTIONARY COMPUTATION 

// THIS FILE PERTAINS TOWARDS AN EXAMPLE OF HOW UTILISING CROSSOVER
// ALLOWS FOR THE GRADUAL MUTATION/REPRODUCTION OF AN ALGORITHM OVER THE COURSE
// OF IT'S RUNTIME

// NESTED INCLUDES

#include "crossover.h"
#include "../util.h"

int main(void)
{
    srand(time(NULL));

    PERSON CURRENT_POPULATION[EC_POP_SIZE];
    PERSON NEW_POPULATION[EC_POP_SIZE];
    CURRENT_CROSSOVER_METHOD = SINGLE;

    printf("HARRY CLARK - EVOLUTIONARY COMPUTATION\n");
    
    EC_STATUS();

    POPULATION_INIT(CURRENT_POPULATION);

    return 0;
}
