// COPYRIGHT (C) HARRY CLARK 2025
// CS3_CI EVOLUTIONARY COMPUTATION 

// THIS FILE PERTAINS TOWARDS AN EXAMPLE OF HOW UTILISING CROSSOVER
// ALLOWS FOR THE GRADUAL MUTATION/REPRODUCTION OF AN ALGORITHM OVER THE COURSE
// OF IT'S RUNTIME

// NESTED INCLUDES

#include "crossover.h"
#include "util.h"

// RANDOMLY CHANGE CHARACTERS WITH BIAS TOWARDS TARGET

void MUTATE(char* MATCH)
{
    int MUTATION_COUNT = 0;
    for(int CHARACTER_INDEX = 0; CHARACTER_INDEX < EC_STRLEN; CHARACTER_INDEX++)
    {
        if(rand() % EC_MAX_GEN < EC_MUT_RATE)
        {
            MUTATION_COUNT++;

            // LEVERAGE GUIDED EVOLUTION FOR MORE PRECISE GENERATIONS
            if(rand() % EC_MAX_GEN < EC_GUIDE_PROB)
            {
                MATCH[CHARACTER_INDEX] = EC_STRING[CHARACTER_INDEX];
            }
            else
            {
                MATCH[CHARACTER_INDEX] = EC_CS + rand() % EC_MAX_GEN;
            }
        }
    }

    if(MUTATION_COUNT > 0)
        ERROR_TRACE(MUT, TRACE_OK, "APPLIED %d MUTATION(S)", MUTATION_COUNT);
}

// PROVIDES SELECTION PRESSURE WHILE MAINTAINING DIVERSITY
// UTILIZES EC_SELECT TO DETERMINE TOURNAMENT SIZE

int SELECTION(PERSON* P)
{
    int BEST_INDEX = rand() % EC_POP_SIZE;
    int BEST_FITNESS = P[BEST_INDEX].WELLBEING;

    for(int TOURNAMENT_INDEX = 1; TOURNAMENT_INDEX < EC_SELECT; TOURNAMENT_INDEX++)
    {
        int COMPETITOR_INDEX = rand() % EC_POP_SIZE;
        if(P[COMPETITOR_INDEX].WELLBEING > BEST_FITNESS)
        {
            BEST_INDEX = COMPETITOR_INDEX;
            BEST_FITNESS = P[COMPETITOR_INDEX].WELLBEING;
        }
    }
    ERROR_TRACE(SELECT, TRACE_ERR_FITNESS, "SELECTED: %d WITH FITNESS LEVEL: %d", BEST_INDEX, BEST_FITNESS);
    return BEST_INDEX;
}

// COMPARISON FUNCTION FOR SORTING BY FITNESS (DESCENDING ORDER)
// USED BY QSORT TO ARRANGE POPULATION FROM FITTEST TO LEAST FIT

int COMPARE_PERSON(const void* PERSON_A, const void* PERSON_B)
{
    PERSON* P_A = (PERSON*)PERSON_A;
    PERSON* P_B = (PERSON*)PERSON_B;
    return P_B->WELLBEING - P_A->WELLBEING;
}
