// COPYRIGHT (C) HARRY CLARK 2025
// CS3_CI GENETIC PROGRAMMING DEMONSTRATION

// THIS FILE PERTAINS TOWARDS THE FUNCTIONALITY ENCOMPASSING A GENETIC PROGRAMMING DEMO
// PRESUPPOSES ALL OF THE CONSTANTS AND FIELDS NEEDED TO REPRESENT A GENERIC GA
//
// ALL OF THIS IS CREATED WITHIN THE SCOPE OF THE MODULES CONTENTS AS PER CS3_CI
// AND MADE WITHIN THE CONTEXT OF PROVIDING A CONTEXTUALISED POINT FOR COMPARISON BETWEEN ALGORITHMS 

#ifndef GP_H
#define GP_H

// SYSTEM INCLUDES

#include <limits.h>
#include <math.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>

#if defined(USE_GP)
    #define USE_GP
#else
    #define USE_GP

    #define     GP_MAX_POP                  100
    #define     GP_MAX_TREE_DEPTH           6

#endif
#endif