// COPYRIGHT (C) HARRY CLARK 2025
// CS3_CI PARTICLE SWARM OPTIMISATION FOR GENETIC PROGRAMMING

// THIS FILE PERTAINS TOWARDS THE MAIN FUNCTIONALITY OF THE PROGRAM

// NESTED INCLUDES

#include "pso.h"

int main(void)
{
    printf("HARRY CLARK - CS3_CI PSO IMPLEMENTATION\n");
    return 0;
}