// COPYRIGHT (C) HARRY CLARK 2025
// CS3_CI PARTICLE SWARM OPTIMISATION FOR GENETIC PROGRAMMING

// THIS FILE PERTAINS TOWARDS THE IMEPLEMENTATION AND MODULARISATION OF THE PSO
// THE FOLLOWING WILL PRESUPPOSE A CURATION OF PARTICLES TO ACT AS A SEPARATED
// COLLECTION OF SOLUTIONS TO CREATE A MORE EFFICIENT SEARCH SPACE FOR A POTENTIAL SOLUTION
//
// SUPPOSE THE BEST COMPARISON COULD BE THAT OF MEMORY ALLOCATION
// WHEREBY LITTLE CHUNKS ARE CREATED TO DELEGATE SPACE FOR ALLOCATION AND DISCERNMENT 
// FOR SOLUTION SPACE

// NESTED INCLUDES

#include "pso.h"

const char* PSO_ERR[] =
{
    "OK",
    "INDEX OUT OF BOUNDS",
    "PARTICLE ERROR",
    "CONVERGENCE ERROR",
    "FITNESS ERROR",
    "DIMENSION ERROR"
};

// INITIALISE THE PSO STATE BASE WITH IT'S DESIGNATED PARAMETERS SUCH AS 
// DIMENSIONS AND FITNESS TYPE, SWARM, BOUNDARIES, ETC 
int PSO_INIT(PSO* PSO_STATE, int DIMENSIONS, PSO_FITNESS_TYPE TYPE)
{
    if(PSO_STATE == NULL) { PSO_MEM_ERROR(PSO_STATE); }

    // DO WE HAVE VALID DIMENSIONS FOR THE SEARCH SPACE 
    if(!PSO_VALID_DIMENSIONS(DIMENSIONS, PSO_MAX_DIMENSIONS + 1)) goto PSO_ERROR_DIM;

    PSO_STATE->DIMENSIONS = DIMENSIONS;
    PSO_STATE->FITNESS = TYPE;
    PSO_STATE->CONV_THRESHOLD = INT_MAX;
    PSO_STATE->SWARM.PARTICLE_PARAMS.COUNT = PSO_MAX_PARTICLES;
    PSO_STATE->SWARM.PARTICLE_PARAMS.CONVERGENCE = 0;
    PSO_STATE->SWARM.PARTICLE_PARAMS.ITERATION = 0;
    PSO_STATE->SWARM.GLOBAL_FITNESS = INT_MAX;

    // INITIALISE THE DEFAULT BOUNDS
    for(int INDEX = 0; INDEX < DIMENSIONS; INDEX++)
    {
        PSO_STATE->BOUNDS_PARAMS.LOWER = -100.0;
        PSO_STATE->BOUNDS_PARAMS.UPPER = 100.0;
    }

    // INITIALISE THE DEFAULT POSITIONING FOR THE GP
    for(int INDEX = 0; INDEX < DIMENSIONS; INDEX++)
    {
        PSO_STATE->SWARM.GLOBAL_POS[INDEX] = 0.0;
    }

    PSO_HANDLE(NONE, PSO_ERROR_NONE, "\nPSO:\n PARTICLES: %d\n DIMENSIONS: %d\n FITNESS: %s\n MAX_ITER: %d\n", 
        PSO_MAX_PARTICLES, DIMENSIONS, PSO_FITNESS_NAME(TYPE), PSO_MAX_ITERATIONS);

    return 0;

    PSO_ERROR_DIM:
        PSO_ERROR_HANDLE(DIMENSIONS, PSO_ERROR_DIM, 
            "INVALID DIMENSION COUNT: %d (MAX: %d)\n", 
            DIMENSIONS, PSO_MAX_DIMENSIONS);
}
