// COPYRIGHT (C) HARRY CLARK 2025
// CS3_CI TRAVELLING SALESMAN PROBLEM 

// THIS FILE PERTAINS TOWARDS THE MODULARISATION OF AREAS ENCOMPASSING THE TSP
// AS PER MODULE AND LAB CONTENTS OF CS3_CI

// NESTED INCLUDES 

#include "tsp.h"

int main(void)
{
    TSP_STATE STATE;
    printf("HARRY CLARK - CS3_CI TSP SOLUTION\n");
    
    TSP_INIT(&STATE);

    TSP_ADD_CITY(&STATE, "LONDON", 0, 0);
    TSP_ADD_CITY(&STATE, "PARIS", 344, 0);
    TSP_ADD_CITY(&STATE, "MADRID", 1495, 173);
    TSP_ADD_CITY(&STATE, "SHANGHAI", 5000, 2812);

    TSP_CALC_DIST(&STATE);
    TSP_NEAREST(&STATE);
    
    return 0;
}
