// COPYRIGHT (C) HARRY CLARK 2025
// CS3_CI TRAVELLING SALESMAN PROBLEM 

// THIS FILE PERTAINS TOWARDS THE MODULARISATION OF AREAS ENCOMPASSING THE TSP
// AS PER MODULE AND LAB CONTENTS OF CS3_CI

// NESTED INCLUDES 

#include "tsp.h"

static int TSP_BEST_DIST;
static int TSP_BEST_PATH[TSP_MAX_CITIES + 1];

// INITIALISE THE ENCOMPASSING BASE FOR THE CURRENT TSP PROBLEM
// THE FOLLIWING WILL LOOK TO DETERMINE THE CITY COUNT, DISTANCES BETWEEN
// CITIES, ETC
//
// ENCORPERATES MATRIX ADDITION TO BE ABLE TO DETERMINE THE BASE
// DISTANCE BETWEEN CITIES
int TSP_INIT(TSP_STATE* STATE)
{
    if(STATE == NULL) { TSP_ERROR(STATE); }

    STATE->CITY_COUNT = 0;
    STATE->DIST.SIZE = 0;
    STATE->TOUR.TSP_TOTAL_DIST = TSP_INF;
    STATE->TOUR.TSP_CITY_COUNT = 0;

    // NOW ITERATE THROUGH EACH OF THE MAX CITIES IN ACCORDANCE
    // WITH THE DISTANCE MATRIX BETWEEN THEM 
    for(int INDEX = 0; INDEX < TSP_MAX_CITIES; INDEX++)
    {
        for(int JINDEX = 0; JINDEX < TSP_MAX_CITIES; JINDEX++)
        {
            // HAVE WE REACHED THE MAX AMOUNT OF ITERATIONS?
            if(STATE->DIST.MATRIX == TSP_INF)
            {
                goto TSP_OOB;
            }

            // ASSIGN THE CORRESPONDING VALUES TO EACH INDEX
            STATE->DIST.MATRIX[INDEX][JINDEX] = (INDEX == JINDEX) ? 0 : TSP_INF;
        }
    }

    TSP_OOB:
        printf("TSP HAS REACHED MAX CITIES LIMIT: %d, EXPECTED: %d\n");
        return 1;

    return 0;
}

int main(void)
{
    TSP_STATE STATE;

    printf("HARRY CLARK - CS3_CI TSP SOLUTION\n");
    return 0;
}
